OceanGlidersCommunity/OG-format-user-manual

OG_Format.adoc

Fixing typos from initial GDoc conversion

---

OG_Format.adoc

This pull-request relates to the issue #24 raised by @justinbuck.

http -> https NERC vocabulary server

---

README.md

as we will add more links here I suggest to be more specific

clarified link to format in README.md

---

src/OG_Vocabulary.adoc

@vturpin and @justinbuck , I'll let for you to verify if the conversion didn't miss anything. I don't have the time now to deal with style adjustments. I'm requesting a review for the content only.

Importing Victor's vocabulary document as ASCIIDoc

---

src/OG_Vocabulary.adoc

should be "Yes" since the link follows

Typo in table for platform type

---

OG_Format.adoc

All these issues were identified by @soerenthomsen while reviewing #35 (first prototype). Thanks, @soerenthomsen !

A few corrections and inconsistencies found on the first prototype

---

.github/workflows/adoc_build.yml

Build the PDF to make it easier to review.

Build OG-Format

---

sp041_20191205T1757.cdl

Missing TELECOM and TRACKING_SYSTEM , following the current standard.

Missing telecom and tracking information

---

OG_Format.adoc

Some parts are not easy to read as it is. No changes on the OG-format, just moving content around and cleaning bad text format.

Organizing text for better reading

---

OG_Format.adoc

Gone through and fixed some typos and made some slight formatting changes. Changed title for the google docs reference in the vocabulary chapter to hopefully make it clearer.

edits from review

---

OG_Format.adoc
history.adoc
sp041_20191205T1757.cdl

An approach to add as much metadata as we think is necessary while keeping some organization. This is the first of a series of PRs (If approved by the group). Let me propose it in parts.
I'll add some information and explanations tomorrow.

Sensors as groups

---

sp041_20191205T1757.cdl

Reported by @kerfoot in #111.
Proponents: @castelao
#111
to merge.

fix: Typo, missing several end of line symbols

---

sp041_20191205T1757.cdl

Moving data into its own groups

---

OG_Format.adoc

Following issue #71 suggestion
Change "Autonomous Underwater Vehicle" into "sub-surface gliders". and link to the proper vocab
Proponents: 
#71 pushed june 2022.
to merge.

Change the vocab for "platform" GA

---

OG_Format.adoc

After #80 suggestion. No Comment since 2 month. PR created
Proponents: 
#80 published in July 2022
to merge.

Global attribute description

---

OG_Format.adoc

gps to GPS for coherency

---

OG_Format.adoc

Rhange link to the control vocab "https://docs.google.com/document/d/1dN90xkw9oCbLs0sPPhOmszdOjLpwcqxiK5mjeZP7abA/edit#" Following #77 submitted 20th of July 2022
Proponents: 
#77 submitted in July 2022
to merge.

Contributor Role vocab

---

OG_Format.adoc

Modification of the first page of the document.
Typo/new introductory titles/etc.
Turn the text into OG1.0 format description and not "toward the harmonization of the existing glider format"
Proponents: 
No issue associated
to merge.

Title / outline / Introduction

---

OG_Format.adoc

Following #81 suggestion made 2 months ago.
Also reshape the table following the GPS variable table stype.
Proponents: 
#81 suggestion was made 2 months ago.
to merge.

Time Valid min/max

---

OG_Format.adoc

Move from long name "ices code" to "ices code of the glider" to make it clearer that we are not talking about the ices code of the ship used to deploy the glider. Following #83 suggestion
Proponents: 
#83 pushed 2 months ago. No comment since. So I push this PR.
to merge.

Change ICES CODE "long name" attribute

---

OG_Format.adoc

Proponents:  @JuangaSocib 
#108 
to merge.
Include a highly recommended sensor attribute for documenting a sensor calibration information document accesible through a permanent URL. This new attribute is scoped to sensors groups.

Adding calibration_link sensor attribute

---

OG_Format.adoc

Following this issue; https://github.com/OceanGlidersCommunity/OG-format-user-manual/issues/108
Adding the :coordinate attribute to "geophisical param"..
Proponents: 
https://github.com/OceanGlidersCommunity/OG-format-user-manual/issues/108
to merge.
This modification will need to update the cdl.

Add coordinates on variable attribute

---

OG_Format.adoc

added CF QC conventions, TIME_GPS clarification and addition context on the parameters section
Proponents: 
to merge.

Update OG_Format.adoc for CF QC fields, parameters & TIME_GPS clarifications

---

OG_Format.adoc

Downgrading, for now, RTQC from mandatory to highly desired.
Proponents: 
to merge.
As decided in meeting 2023-04-24.

RTQC methods downgraded to highly-desirable

---

OG_Format.adoc

Proponents: 
See issue  #43  for related discussion
to merge.

"_FillValue" instead of "FillValue" everywhere

---

OG_Format.adoc

updated PLATFORM_CODE to PLATFORM_NAME
Proponents: 
to merge.

Update OG_Format.adoc - PLATFORM_CODE to PLATFORM_NAME

---

OG_Format.adoc

Proponents: 
- [x ] Addition that does not require change in the current structure.
to merge.

add emodnet to supporters

---

OG_Format.adoc

institution is used twice in the global attribute. institution is a cf attribute with its own definition. While agency refers to the agencies involved in the glider mission (operating agency, funding agency, etc.)
Proponents: 
to merge.

change institution to agency in .adoc file

---

OG_Format.adoc

add "and GPS location" in the TIME variable for consistency and clarity
Proponents: 
to merge.

add "and GPS location" in the TIME variable in .adoc file

---

OG_Format.adoc

change location of "data_mode" as it was not relevant in the TRAJECTORY variable. In fact, data_mode is part of the "id" but not of the "TRAJECTORY".
Proponents: 
to merge.

change reference to <data_mode> in .adoc file

---

examples/minimal.cdl

Here I propose the minimal .cdl
I've removed everything that is not mandatory.
This is align with the status of the format the 14th of February 2024 with downgrading of PARAMETER and SENSOR informations.
Impact should be low as the agreement on what is mandatory in OG.1.0 is pretty weak. But a final check is necessary before release.
Proponents: 
to merge.

Create folder with exemplar - create minimal.cdl

---

og_format_examples_files/README.md

fix: sp041 is a Spray platform

---

OG_Format.adoc

Following #174 discussion. I clarified the concept of platform with an hopefully clearer definition.  I also remove the reference to "platform_type" in the control vocabulary table as this concept is not used in the format.
Proponents: 
to merge.

Platform and platform type update

---

OG_Format.adoc

Proponents: @castelao
to merge.

Missing standard_name for TIME & TIME_GPS

---

OG_Format.adoc

* remone note and image about program. 
* Program will be managed as a control vocabulary
Proponents: 
to merge.

update program attribute.adoc

---

vocabularyCollection/tableOfControlledVocab.adoc

I've made some large changes to split out the mandatory and high desirable metadata fields. 
Also added some text about requesting new terms. We need to decide on labels for new vocab issues.
Proponents: 
to merge.

Updated vocab doc - highly desirable table is still to update

---

OG_Format.adoc

* Reference to plaform name
* correction on platform exemplar in the global attribute
Proponents: 
to merge.

plafrom_name consistency.adoc

---

OG_Format.adoc

fix table bug.adoc

---

OG_Format.adoc

#216
Proponents: 
see issue #216

Update OG_Format - add exemplar for url and doi.adoc

---

vocabularyCollection/phase.md

related to #226
Proponents: 
to merge.

Add ids to phase variables.md

---

vocabularyCollection/tableOfControlledVocab.adoc

Add reference to QC_flag vocab.adoc

---

OG_Format.adoc

per issue 238 - adjusts format description for trajectory var
Proponents: @jenseva, @emmerbodc 
- [x ] Typo without possible change of interpretation of the related text.
See issue 238 for discussion of these changes.
to merge.

Update Trajectory format in OG_Format.adoc

---

vocabularyCollection/tableOfControlledVocab.adoc

role linked to W08, 
added sensor maker on same line as platform maker
added in production link to glider sensors

added glider sensors  & W08 collection for role

---

vocabularyCollection/phase.md

from slocum engineer
Proponents: 
to merge.

suggestion for phase description updates

---

OG_Format.adoc

Add standard_name description and table link
