OceanGlidersCommunity/OG-format-user-manual

- Toward_the_evolving_OG_format_manual.md
- Toward_the_official_version_of_the_OG_format_manual.md
Since we moved to GitHub, let's avoid confusion. It is lacking some
style formatting, but all the content was moved, so let's remove this
links to the original document and now on do all the modifications at
GitHub.
Those two files were from before the decision of moving the content to here.
> Removing links to original Google Document

- OG_Format.adoc
Keep the document clean and short.
On the top of the example files, we should add plenty of examples in the document to help the reader, such as the ones added by @vturpin. To avoid a way too long document, what about collecting the examples in the appendix?
> Moving examples to an appendix

- README.md
I linked the source file of the CoC from the OceanGliders repo and suggest we remove the CODE_OD_CONDUCT.md source file to avoid confusion especially in case we update it. @castelao what do you think?
> link CoC in README

- .github/CODEOWNERS
This list was defined by @vturpin based on the original authors of OG-1.0 to speed up the approval procedure of final adjustments and corrections.
> Creating list of code owners

- OG_Format.adoc
Thanks to @soeren who noticed that on PR #35.
> Missing standard_name for GPS lat & lon

- OG_Format.adoc
It's a free field as long as it is unique, but ACDD recommends using reverse-DNS. Adding an example.
> naming authority

- OG_Format.adoc
- sp041_20191205T1757.cdl
- I believe that at some point, the deployment time was accepted as double, which requires some attributes to make sense of it.
- It doesn't make sense to use String for deployment lat/lon, right?
I think this was identified by @vturpin.
> Improve deployment variables

- OG_Format.adoc
@vturpin noticed on #76 that `Conventions` was not required. This is an important field to guide expected behavior for applications. This is too easy to set up, and no reason to don't be mandatory.
- Following @vturpin , Conventions should be mandatory
- CF-1.9 is backward compatible hence it also satisfies CF-1.8
> Conventions as mandatory

- README.md
Let's point to the HTML instead of the adoc since it is easier to read.
> Updating link to compiled document

- OG_Format.adoc
@vturpin noticed that the title definition was misleading, suggesting a
fixed value. Adding an exemple in front of it should be clear enough
that it is an example, not a fixed text. That requires changing the
column header.
> Clarify that title is not a fixed value

- OG_Format.adoc
Following recommendation of #102 to clarify how to manage fix values
Proponents: 
The suggestion made by @castelao has been made a month ago. 
So I push a PR to close the issue
to merge.
> FillValue for PARAM

- OG_Format.adoc
Removed Reporting and Agenda sections and modified best practices section. I am not sure if DMTT should review OBP submissions before tagging them as OG, or if submitter can do it using their own judgment.
Proponents: 
to merge.
> Remove Reporting, Agenda, updating Best Practices policy

- .github/CODEOWNERS
Proponents: 
to merge.
I just noticed that it was missing @emmerbodc  in the list of reviewers.
> Missing Emma in the code reviewers.

- OG_Format.adoc
There was a typo in the table parameter that impact the display of the table. "|" was missing at the end of each row.
Proponents: 
to merge.
> typo in the table of parameter

- OG_Format.adoc
I removed RTQC reference in the global attribute following recommendation made in issue #170 . The only reference to RTQC is made at the PARAM variable level now.
Proponents: 
to merge.
> remove RTQC from global attribute.adoc

- README.md
Proponents: 
This PR updates the link on the README to the new url of the format on github pages.
I had to change the Settings/Pages source to get github to load the new pages build. You should be able to reach web pages of the format, vocabularies and history from the readme. Let me know if it's not intuitive @emmerbodc @vturpin
> Update link to OGformat to new GH pages site

- OG_Format.adoc
Remove both dimension and adapt the doc to this changes. Remove the PARAMETER's information section that is becoming unecessary and redondant with PARAM attributes and SENSOR attributes Create empty and dimensionless SENSOR variable with attribute describing the sensor. Adjust text a little bit.
Proponents: 
#184 
This PR is not 100% align with Emma's cdl but I think it is improving the format, simplying it and avoiding redondancies (ex. units)
> Remove dimension N_SENSOR and N_PARAM.adoc

- OG_Format.adoc
To clean the doc and not loosing this important comment I remove the bottom page note and turn it into an issue for future release (OG1.X)
Proponents: 
#226
> Remove note about QC flag.adoc

- OG_Format.adoc
remove *_id* for coherence in the way we refere to vocabs and reorganize the line.
Proponents: 
#226
> contributing_institution_id.adoc

- OG_Format.adoc
No exemplar yet for field comp'
exemplar for telecom and hardware refers to Vocab guildeline. But as the controlled vocab are pending (not served by a vocabulary server yet, I do not know how i should fill the `*_vocabulary` attribute.
Proponents: 
#222
> add exemplar for telecom, hardware and field comparison.adoc

- OG_Format.adoc
Modifies the PARAM documentation section in in  OG_Format.adoc. 
Per @emmerbodc - agreed in meeting yesterday, coordinates needs re-ordering based on most popular standard.
Proponents: @jenseva
- [ x] Fix of some error, inconsistency, unforeseen limitation.
See issue #240 for related discussion
[https://github.com/OceanGlidersCommunity/OG-format-user-manual/issues/240](https://github.com/OceanGlidersCommunity/OG-format-user-manual/issues/240)
to merge.
> Reorder listing of coordinates in PARAM attribute documentation

- OG_Format.adoc
Bring coherence on how data type and dimension are notified in the doc.
Proponents: 
#246 
I've remove one sentance about phase that was not correct.
> coherence in data type and dimension.adoc

- .github/CODEOWNERS
Proponents: 
Following today's meeting, propose adding @jenseva to codeowners so she can review PRs.
As always, this will require two approvals! @emmerbodc  @vturpin
> Add Jenn to codewowners

- README.md
With more people using it, we should get more feedback on the OG-1.0 format and the checker itself. Helping new users adopt the format should help mature the full ecosystem.
Proponents: 
Related to #256. Once that issue is resolved, an update will be required on the checker.
to merge.
> Adding a link to the OG format checker

- OG_Format.adoc
Proponents: 
Proposed to resolve #273 
This adds SEGMENT_NUMBER (surfacing to surfacing) and PROFILE_NUMBER (each time the glider starts a new dive/climb).
How does this look? @emmerbodc @vturpin
> propose segment and profile variables
